# Generated by Django 5.1.14 on 2025-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='description',
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.TextField(default='Ingrédients à définir'),
        ),
        migrations.AddField(
            model_name='recette',
            name='instructions',
            field=models.TextField(default='Instructioons à définir'),
        ),
    ]
